base = "ethereum"

name = "XO Chain"
id = 3223

# Disable features not applicable to XO Chain
flashbots_enabled = false
eip7702_enabled = false
eip7623_enabled = false

# Low minimum priority fee for XO Chain
min_max_priority_fee_per_gas = 0

block_gas_limit = 30000000
max_transaction_size_bytes = 256000
